Who wrote this/Controllers/AnwerController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Who_wrote_this.Models;

namespace Who_wrote_this.Controllers
{
    public class AnswerController : Controller
    {
        private readonly IAnswerRepository _answerRepository;

        public AnswerController(IAnswerRepository answerRepository)
        {
            this._answerRepository = answerRepository;
        }

        // GET: AnswerController
        public ActionResult Index()
        {
            var answers = _answerRepository.GetAll();
            return View(answers);
        }

        // GET: AnswerController/Details/5
        public ActionResult Details(int id)
        {
            var answer = _answerRepository.GetById(id);
            return View(answer);
        }

        // GET: AnswerController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AnswerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AnswerController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: AnswerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AnswerController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AnswerController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Who wrote this/Controllers/AuthorController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Who_wrote_this.Models;

namespace Who_wrote_this.Controllers
{
    public class AuthorController : Controller
    {
        private readonly IAuthorsRepository _authorsRepository;

        public AuthorController(IAuthorsRepository authorsRepository)
        {
            this._authorsRepository = authorsRepository;
        }
        // GET: AuthorController
        public ActionResult Index()
        {
            var authors = _authorsRepository.GetAll();
            return View(authors);
        }

        // GET: AuthorController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AuthorController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AuthorController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Author collection)
        {
            try
            {
                var authorId = 1;
                if (_authorsRepository.GetAll().Any())
                    authorId = _authorsRepository.GetAll().Last().Id + 1;

                var author = new Author
                {
                    Id = authorId,
                    Name = collection.Name
                };

                _authorsRepository.Add(author);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AuthorController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: AuthorController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AuthorController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AuthorController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Who wrote this/Controllers/QuestionAnswerController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Who_wrote_this.Models;

namespace Who_wrote_this.Controllers
{
    public class QuestionAnswerController : Controller
    {
        private readonly IAuthorsRepository _authorsRepository;
        private readonly IQuestionRepository _questionRepository;
        private readonly IAnswerRepository _answerRepository;

        public QuestionAnswerController(IAuthorsRepository authorsRepository, IQuestionRepository questionRepository, IAnswerRepository answerRepository)
        {
            this._authorsRepository = authorsRepository;
            this._questionRepository = questionRepository;
            this._answerRepository = answerRepository;
        }

        // GET: QuestionAnswerController
        public ActionResult Index()
        {
            return RedirectToAction(nameof(this.Create));
        }

        // GET: QuestionAnswerController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: QuestionAnswerController/Create
        public ActionResult Create()
        {
            var model = new QuestionAnswer();
            model.AuthorsId = _authorsRepository.GetAll().Select(x => x.Id).ToList();
            return View(model);
        }

        // POST: QuestionAnswerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(QuestionAnswer collection)
        {
            try
            {
                var author = _authorsRepository.GetById(collection.AuthorIdSelected);
                var answerId = 1;
                var answersList = new List<Answer>();
                var interationCount = 1;

                var questionId = 1;
                if (_questionRepository.GetAll().Any())
                    questionId = _questionRepository.GetAll().Last().Id + 1;

                var question = new Question
                {
                    Id = questionId,
                    Title = collection.Title,
                    Author = author,
                    Description = collection.Question,
                    Answers = answersList
                };

                foreach (var item in collection.Answers)
                {
                    var isAccepted = false;
                    if (interationCount == collection.AcceptAnswer) isAccepted = true;

                    interationCount++;

                    if (_answerRepository.GetAll().Any())
                        answerId = _answerRepository.GetAll().Last().Id + 1;

                    var answer = new Answer
                    {
                        Id = answerId,
                        Author = author,
                        Question = question,
                        IsAccepted = isAccepted,
                        Description = item
                    };
                    _answerRepository.Add(answer);
                    answersList.Add(answer);
                }

                _questionRepository.Add(question);

                return RedirectToAction("Index", "Question");
            }
            catch
            {
                return View();
            }
        }

        // GET: QuestionAnswerController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: QuestionAnswerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: QuestionAnswerController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: QuestionAnswerController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Who wrote this/Controllers/QuestionController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Who_wrote_this.Models;

namespace Who_wrote_this.Controllers
{
    public class QuestionController : Controller
    {
        private readonly IQuestionRepository _questionRepository;

        public QuestionController(IQuestionRepository quesionRepository)
        {
            this._questionRepository = quesionRepository;
        }

        // GET: QuestionController
        public ActionResult Index()
        {
            var questions = _questionRepository.GetAll();
            return View(questions);
        }

        // GET: QuestionController/Details/5
        public ActionResult Details(int id)
        {
            var question = _questionRepository.GetById(id);
            return View(question);
        }

        // GET: QuestionController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: QuestionController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: QuestionController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: QuestionController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: QuestionController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: QuestionController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Who wrote this/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Who_wrote_this</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Who_wrote_this.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Who_wrote_this</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="QuestionAnswer" asp-action="Index">Create the question</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="Index">Author</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Question" asp-action="Index">Question</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Answer" asp-action="Index">Answer</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Who_wrote_this - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>